### ISSUE TITLE
css with base64

### ISSUE THREAD

**Issue by b2whats** [mariocasciaro/gulp-concat-css#16]
BEFORE
> background: url(**'**data:image/png;base64,iVBORw.......Jggg==**'**) no-repeat scroll 100% 50% rgba(0, 0, 0, 0);

AFTER
> background: url(data:image/png;base64,iVBORw.......Jggg==**"**) no-repeat scroll 100% 50% rgba(0, 0, 0, 0);

disappear quotes

**Comment by mariocasciaro** [comment]
That is still a valid URI unless it contains special characters that must be quoted. Is that creating any problem in you CSS?

**Comment by b2whats** [comment]
is valid, but because of the quotes in the code editor ceases to be formatted
http://joxi.ru/V2VepwBsB4xXmv.jpg

**Comment by mariocasciaro** [comment]
The screenshot shows that there is an extra quote, which is not right. Will add a unit test to try to reproduce.

**Comment by feiqitian** [comment]
BEFORE:
background: url("data:image/gif;**base64**,R0lGODlhF...ABAAAIBADpBQQAOw==") no-repeat;
AFTER:
background: url(data:image/gif;**base6**,R0lGODlhF...ABAAAIBADpBQQAOw==") no-repeat;

base64 --> base6

**Comment by mariocasciaro** [comment]
Yes apparently the problem is in the package rework-plugin-function which doesn't parse the url properly. Will try to open a defect send a PR.

**Comment by mariocasciaro** [comment]
Landend in 2.0.0.
