### ISSUE TITLE
Error when file contains keyframe animations

### ISSUE THREAD

**Issue by jdwillemse** [mariocasciaro/gulp-concat-css#17]
When using concat on a a file with @keyframes my build fails.

This is the error:
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Cannot call method 'forEach' of undefined
```

I have reproduced this on a css file containing just:
```
@keyframes NAME-YOUR-ANIMATION {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}
```

**Comment by mariocasciaro** [comment]
I run a test and apparently I cannot reproduce. Could you please send some code which would help me reproduce? Also, what's exactly the error?

**Comment by jdwillemse** [comment]
I have tried reproducing it on a blank project and failed. I then went back to where I had the problem initially and couldn't reproduce it either. 

The only Thing that changed on my side is that I updated node.js (which was quite old) and then updated my NPM packages. I think this issue must have been caused by my outdated setup. 

Apologies for the false alarm.
