### ISSUE TITLE
Breaks on properties with an inline comment including curly braces

### ISSUE THREAD

**Issue by cimmone** [mariocasciaro/gulp-concat-css#21]
Essentially, the following doesn't work correctly, and throws errors rather than actually accepting it as valid css:

a {color: #000 /\*{a}\*/;}

There were some other combinations with braces inside comments that cause problems, but it's hard to tell if they all have the same underlying problem or not.

**Comment by mariocasciaro** [comment]
Sounds strange, could you please post the error you get?
