### ISSUE TITLE
url

### ISSUE THREAD

**Issue by Aligan** [mariocasciaro/gulp-concat-css#32]
Hi.
task
gulp.task('cssup', function() {
    return gulp.src('./app/css/**/*.css')
        .pipe(concatCss("all.css"))
        .pipe(cssmin())
        .pipe(rename('all.min.css'))
        .pipe(gulp.dest('dist/'))
        .pipe(reload({stream:true}));
});

result:
background: url("../../../../../../images/bg-h-ico.png") no-repeat;

How use includePats?

**Comment by mariocasciaro** [comment]
Please refer to this post: https://github.com/mariocasciaro/gulp-concat-css/issues/29

**Comment by Aligan** [comment]
Thank you
