### ISSUE TITLE
Imported files saved with original path included

### ISSUE THREAD

**Issue by Omranic** [mariocasciaro/gulp-concat-css#41]
I'm just wondering why this package save files with their original path included?!

### Usage
```javascript
var gulp = require('gulp');
var concatCss = require('gulp-concat-css');
 
gulp.task('default', function () {
  return gulp.src('assets/css/app.css')
    .pipe(concatCss("styles/bundle.css"))
    .pipe(gulp.dest('out/'));
});
```

### Expected
```
out/styles/bundle.css
```

### Current
```
out/assets/css/styles/bundle.css
```

And I can see it's intentional and can't be overridden by options, don't you think this needs to be flexible?
https://github.com/mariocasciaro/gulp-concat-css/blob/master/index.js#L120

**Comment by mariocasciaro** [comment]
You need to set the right base for gulp.src:

```javascript
gulp.src([...your assets...], {base: 'assets'})
```
